services:
  postgres:
    image: postgres:16
    container_name: ${PG_CONTAINER:-orgmgr-pg}
    environment:
      POSTGRES_DB: ${PG_DB:-studs}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
    ports:
      - "${PG_PORT:-5432}:5432"

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: ${MINIO_CONTAINER:-orgmgr-minio}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    #volumes:
    #  - ./build/minio/data:/data
